version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3.7.24-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres-timescale:
    image: timescale/timescaledb:latest-pg10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
    - /var/lib/postgresql:/var/lib/postgresql
  redis:
    image: redis
    ports:
      - "6379:6379"
   
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "7070:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@harksys.com
      - PGADMIN_DEFAULT_PASSWORD=password