version: '3.3'
services:
  postgres-timescale:
    image: timescale/timescaledb:latest-pg10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
    - /var/lib/postgresql:/var/lib/postgresql
   
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "7070:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@hello.com
      - PGADMIN_DEFAULT_PASSWORD=password